---

exclude:
  - aws-elb-alb-not-public
  - aws-s3-enable-bucket-logging
  - aws-vpc-add-description-to-security-group-rule
  - aws-vpc-no-public-egress-sgr
  - aws-vpc-no-public-ingress-sgr
  - aws-ec2-require-vpc-flow-logs-for-all-vpcs
